version: "3.9"

services:

  redis:
    image: redis:7-alpine
    container_name: routerx-redis
    restart: always


  api:
    build: .
    container_name: routerx-api
    restart: always
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      PORT: 3000
      DOCKER: "true"
    ports:
      - "3000:3000"
    volumes:
      - routerx_data:/app/data
    depends_on:
      - redis


  worker:
    build: .
    container_name: routerx-worker
    restart: always
    command: node dist/workers/monitor.worker.js
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      DOCKER: "true"
    volumes:
      - routerx_data:/app/data
    depends_on:
      - redis


volumes:
  routerx_data:

